name: aipowered
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI and Fonts
  google_fonts: ^6.3.2
  lottie: ^3.3.2

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_database: ^12.0.2
  google_sign_in: ^7.2.0

  #icon
  flutter_launcher_icons: ^0.14.4

  # Chatbot and API
  http: ^1.5.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter_launcher_icons:
  android: true      # Use true to auto-generate icons for Android
  ios: true          # Use true for iOS icons
  image_path: "assets/icon/icon.png"  # Path to your icon image


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/videos/animation.json
    - assets/images/google.png
    - assets/icon/icon.png
    - .env
